version: '3.8'

services:
  web:
    build: ./nginx-php
    container_name: lamp_web
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - web_data:/var/www/html
    networks:
      - lamp_network

  db:
    image: mariadb:10.5-alpine
    container_name: lamp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lamp_network

volumes:
  db_data:
  web_data:

networks:
  lamp_network:
    driver: bridge
